//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockPortfolioApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockPortfolioDBEntities : DbContext
    {
        public StockPortfolioDBEntities()
            : base("name=StockPortfolioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblBalance> tblBalances { get; set; }
        public virtual DbSet<tblCurrency> tblCurrencies { get; set; }
        public virtual DbSet<tblEquity> tblEquities { get; set; }
        public virtual DbSet<tblPortfolioHolding> tblPortfolioHoldings { get; set; }
        public virtual DbSet<tblPortfolio> tblPortfolios { get; set; }
        public virtual DbSet<tblStockExchanx> tblStockExchanges { get; set; }
        public virtual DbSet<tblTransactionDividend> tblTransactionDividends { get; set; }
        public virtual DbSet<tblTransactionEquity> tblTransactionEquities { get; set; }
        public virtual DbSet<tblTransactionFinance> tblTransactionFinances { get; set; }
        public virtual DbSet<tblTransactionType> tblTransactionTypes { get; set; }
    }
}
