//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockPortfolioApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEquity()
        {
            this.tblPortfolioHoldings = new HashSet<tblPortfolioHolding>();
            this.tblTransactionDividends = new HashSet<tblTransactionDividend>();
            this.tblTransactionEquities = new HashSet<tblTransactionEquity>();
        }
    
        public int EquityID { get; set; }
        public Nullable<int> ExchangeIDFK { get; set; }
        public string StockTicker { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
        public Nullable<bool> HasDividend { get; set; }
    
        public virtual tblStockExchanx tblStockExchanx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPortfolioHolding> tblPortfolioHoldings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransactionDividend> tblTransactionDividends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransactionEquity> tblTransactionEquities { get; set; }
    }
}
