//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockPortfolioApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockExchanx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStockExchanx()
        {
            this.tblEquities = new HashSet<tblEquity>();
        }
    
        public int ExchangeID { get; set; }
        public Nullable<int> CurrencyIDFK { get; set; }
        public string ExchangeName { get; set; }
        public string ExchangeDescription { get; set; }
    
        public virtual tblCurrency tblCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEquity> tblEquities { get; set; }
    }
}
