//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockPortfolioApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransactionEquity
    {
        public int TransactionID { get; set; }
        public Nullable<int> EquityIDFK { get; set; }
        public Nullable<int> AccountIDFK { get; set; }
        public Nullable<int> TransactionTypeIDFK { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> Shares { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblEquity tblEquity { get; set; }
        public virtual tblTransactionType tblTransactionType { get; set; }
    }
}
